# Tensorflow Basics

In [67]:
import tensorflow as tf

Tensorflow works on graph computational model where graphs are created and executed as follows:
    1. Define edges (sources)
    2. Define nodes (computations)
    3. Start session to build graph

Source operations or **source ops** do not need any information input. They pass information to other operations which perform computations. 

The following source op defines two constants.

In [68]:
a = tf.constant([2])
b = tf.constant([3])

Computational nodes perform operations on source ops. We define a node **c** which adds **a** and **b**.

In [69]:
c = tf.add(a, b)

We initialize a session to start the graph and run the nodes withing the session.

In [70]:
session = tf.Session()

In [71]:
result = session.run(c)

In [72]:
print(result, type(result))

[5] <class 'numpy.ndarray'>


Sessions need to be closed after the graph is built to release resources.

In [73]:
session.close()

**with** statement can be used to perform the session initialize and close within a code block.

In [74]:
with tf.Session() as session:
    result = session.run(c)
    print(result, type(result))

[5] <class 'numpy.ndarray'>


## Tensors

**Tensors are 3-dimensional nd-arrays**.

1-d : scalar

2-d : vector

3-d : matrix

**4-d : tensor**

In [75]:
scalar = tf.constant([2])

vector = tf.constant([7, 6, 5])

matrix = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

tensor = tf.constant([[[1, 2, 3], [2, 3, 4], [3, 4, 5]], 
                      [[4, 5, 6], [5, 6, 7], [6, 7, 8]], 
                      [[7, 8, 9], [8, 9, 1], [9, 1, 2]]])

with tf.Session() as session:
    result = session.run(scalar)
    print("Scalar (1 entry): \n {0} \n {1} \n".format(result, scalar))
    result = session.run(vector)
    print("Vector (3 entries): \n {0} \n {1} \n".format(result, vector))
    result = session.run(matrix)
    print("Matrix (3x3 entries): \n {0} \n {1} \n".format(result, matrix))
    result = session.run(tensor)
    print("Tensor (3x3x3 entries): \n {0} \n {1} \n".format(result, tensor))

Scalar (1 entry): 
 [2] 
 Tensor("Const_15:0", shape=(1,), dtype=int32) 

Vector (3 entries): 
 [7 6 5] 
 Tensor("Const_16:0", shape=(3,), dtype=int32) 

Matrix (3x3 entries): 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
 Tensor("Const_17:0", shape=(3, 3), dtype=int32) 

Tensor (3x3x3 entries): 
 [[[1 2 3]
  [2 3 4]
  [3 4 5]]

 [[4 5 6]
  [5 6 7]
  [6 7 8]]

 [[7 8 9]
  [8 9 1]
  [9 1 2]]] 
 Tensor("Const_18:0", shape=(3, 3, 3), dtype=int32) 



In [76]:
matrix_one = tf.constant([[1, 2, 3], [2, 3, 4], [3, 4, 5]])
matrix_two = tf.constant([[1, 1, 1], [1, 1, 1], [1, 1, 1]])

first_addition = tf.add(matrix_one, matrix_two)
second_addition = matrix_one + matrix_two

with tf.Session() as session:
    result = session.run(first_addition)
    print(result, "\n")
    result = session.run(second_addition)
    print(result)

[[2 3 4]
 [3 4 5]
 [4 5 6]] 

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [77]:
first_multiplication = tf.multiply(matrix_one, matrix_two)
second_multiplication = tf.multiply(matrix_one, matrix_two)
third_multiplication = tf.matmul(matrix_one, matrix_two)

with tf.Session() as session:
    result = session.run(first_multiplication)
    print("Element-wise multiplication 1: \n", result)
    result = session.run(second_multiplication)
    print("Element-wise multiplication 2: \n", result)
    result = session.run(third_multiplication)
    print("Matrix multiplication: \n", result)

Element-wise multiplication 1: 
 [[1 2 3]
 [2 3 4]
 [3 4 5]]
Element-wise multiplication 2: 
 [[1 2 3]
 [2 3 4]
 [3 4 5]]
Matrix multiplication: 
 [[ 6  6  6]
 [ 9  9  9]
 [12 12 12]]


## Variables

A TensorFlow variable is the best way to represent shared, persistent state manipulated by your program. A **tf.Variable()** represents a tensor whose value can be changed by running ops on it. Tensorflow variables are **mutable**. Variables once created, needs to be initialized before running the graph session. 

The following code demonstrate how to create and initialize a vaiable in Tensorflow.

In [78]:
#create a variable with initial value 0
state = tf.Variable(0)
print(type(state))

<class 'tensorflow.python.ops.variables.Variable'>


In [79]:
one = tf.constant(1)

#create a new vaue by adding constant one to variable state
new_value = tf.add(state, one)

#update the state variable with new_value
update = tf.assign(state, new_value)

Variables are initialized by calling the function **tf.global_variables_initializer()**

In [80]:
init_op = tf.global_variables_initializer()

In [81]:
with tf.Session() as session:
    session.run(init_op)
    print("Initial state: ", session.run(state))
    for _ in range(4):
        session.run(update)
        print("State after next update: ", session.run(state))

Initial state:  0
State after next update:  1
State after next update:  2
State after next update:  3
State after next update:  4


## Placeholder

Tensorflow placeholders act as placefolders for a tensor to which data needs to be fed. These are like "holes" in the model that need to be filled with data.

In the following code we create a placeholder (*hole* a) and use it inside a model (operation b = a * 2).

In [82]:
a = tf.placeholder(tf.float32)

In [83]:
b = a * 2

This hole needs to be filled with data before running otherwise it would throw an error. We can fill the placeholder with data using **feed_dict** dictionaries as parameters within **run**.

In [84]:
with tf.Session() as sess:
    feed_dict = {a : 2.5}
    result = sess.run(b,feed_dict=feed_dict)
    print (result)

5.0


In [85]:
dictionary={a: [ [ [1,2,3],[4,5,6],[7,8,9],[10,11,12] ] , [ [13,14,15],[16,17,18],[19,20,21],[22,23,24] ] ] }

with tf.Session() as sess:
    result = sess.run(b,feed_dict=dictionary)
    print (result)

[[[  2.   4.   6.]
  [  8.  10.  12.]
  [ 14.  16.  18.]
  [ 20.  22.  24.]]

 [[ 26.  28.  30.]
  [ 32.  34.  36.]
  [ 38.  40.  42.]
  [ 44.  46.  48.]]]


In [86]:
import numpy as np

In [87]:
x = tf.placeholder(tf.int32, shape=(3, 3))
y = tf.matmul(x, x)

with tf.Session() as sess:
    #print(sess.run(y))  #ERROR: will fail because x was not fed with data.
    
    rand_array = np.random.randint(5, size = (3, 3))
    print(rand_array, "\n")
    print(sess.run(y, feed_dict={x: rand_array}))
    print(y.shape, type(y))

[[4 4 3]
 [3 0 1]
 [3 1 2]] 

[[37 19 22]
 [15 13 11]
 [21 14 14]]
(3, 3) <class 'tensorflow.python.framework.ops.Tensor'>
