# Tensorflow Basics

In [23]:
import tensorflow as tf

Tensorflow works on graph computational model where graphs are created and executed as follows:
    1. Define edges (sources)
    2. Define nodes (computations)
    3. Start session to build graph

Source operations or **source ops** do not need any information input. They pass information to other operations which perform computations. 

The following source op defines two constants.

In [24]:
a = tf.constant([2])
b = tf.constant([3])

Computational nodes perform operations on source ops. We define a node **c** which adds **a** and **b**.

In [25]:
c = tf.add(a, b)

We initialize a session to start the graph and run the nodes withing the session.

In [26]:
session = tf.Session()

In [27]:
result = session.run(c)

In [28]:
print(result, type(result))

[5] <class 'numpy.ndarray'>


Sessions need to be closed after the graph is built to release resources.

In [29]:
session.close()

**with** statement can be used to perform the session initialize and close within a code block.

In [30]:
with tf.Session() as session:
    result = session.run(c)
    print(result, type(result))

[5] <class 'numpy.ndarray'>


## Tensors

**Tensors are 3-dimensional nd-arrays**.

1-d : scalar

2-d : vector

3-d : matrix

**4-d : tensor**

In [42]:
scalar = tf.constant([2])

vector = tf.constant([7, 6, 5])

matrix = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

tensor = tf.constant([[[1, 2, 3], [2, 3, 4], [3, 4, 5]], 
                      [[4, 5, 6], [5, 6, 7], [6, 7, 8]], 
                      [[7, 8, 9], [8, 9, 1], [9, 1, 2]]])

with tf.Session() as session:
    result = session.run(scalar)
    print("Scalar (1 entry): \n {0} \n {1} \n".format(result, scalar))
    result = session.run(vector)
    print("Vector (3 entries): \n {0} \n {1} \n".format(result, vector))
    result = session.run(matrix)
    print("Matrix (3x3 entries): \n {0} \n {1} \n".format(result, matrix))
    result = session.run(tensor)
    print("Tensor (3x3x3 entries): \n {0} \n {1} \n".format(result, tensor))

Scalar (1 entry): 
 [2] 
 Tensor("Const_31:0", shape=(1,), dtype=int32) 

Vector (3 entries): 
 [7 6 5] 
 Tensor("Const_32:0", shape=(3,), dtype=int32) 

Matrix (3x3 entries): 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
 Tensor("Const_33:0", shape=(3, 3), dtype=int32) 

Tensor (3x3x3 entries): 
 [[[1 2 3]
  [2 3 4]
  [3 4 5]]

 [[4 5 6]
  [5 6 7]
  [6 7 8]]

 [[7 8 9]
  [8 9 1]
  [9 1 2]]] 
 Tensor("Const_34:0", shape=(3, 3, 3), dtype=int32) 

